import type { Question } from "@/lib/types";

// Seed bank. Self-authored, EPSO-style single-best-answer MCQs.
// NOT official EPSO material. The "generate more" feature appends to this at runtime.
export const SEED_QUESTIONS: Question[] = [
  // ---------------- EU AI ACT ----------------
  {
    id: "aiact-01",
    topic: "ai-act",
    stem: "Under the EU AI Act (Reg. 2024/1689), which risk category do AI systems used for social scoring by public authorities fall into?",
    choices: {
      A: "High-risk, permitted with conformity assessment",
      B: "Limited-risk, transparency obligations only",
      C: "Prohibited (unacceptable risk)",
      D: "Minimal-risk, no obligations",
    },
    answer: "C",
    explanation:
      "Social scoring by public authorities is a prohibited practice under Article 5 (unacceptable risk).",
  },
  {
    id: "aiact-02",
    topic: "ai-act",
    stem: "The EU AI Act classifies AI systems primarily according to:",
    choices: {
      A: "The programming language used",
      B: "The level of risk they pose",
      C: "The size of the provider organisation",
      D: "The country of deployment",
    },
    answer: "B",
    explanation:
      "It is a risk-based framework: unacceptable / high / limited / minimal risk.",
  },
  {
    id: "aiact-03",
    topic: "ai-act",
    stem: "Which of the following is a 'high-risk' AI system under the AI Act?",
    choices: {
      A: "A spam filter",
      B: "An AI system used to evaluate candidates in recruitment",
      C: "A video-game NPC behaviour engine",
      D: "A product-recommendation widget",
    },
    answer: "B",
    explanation:
      "AI used in employment/recruitment is listed as high-risk in Annex III.",
  },
  {
    id: "aiact-04",
    topic: "ai-act",
    stem: "General-Purpose AI (GPAI) models with 'systemic risk' are presumed when training compute exceeds a threshold measured in:",
    choices: {
      A: "Number of parameters only",
      B: "Floating-point operations (FLOPs) used in training",
      C: "Gigabytes of training data",
      D: "Number of end users",
    },
    answer: "B",
    explanation:
      "The Act uses a cumulative training-compute (FLOPs) threshold to presume systemic risk.",
  },
  {
    id: "aiact-05",
    topic: "ai-act",
    stem: "Which obligation applies to a limited-risk system such as a chatbot interacting with humans?",
    choices: {
      A: "Full conformity assessment before market placement",
      B: "Transparency: users must be informed they are interacting with an AI",
      C: "Prohibition",
      D: "No obligation whatsoever",
    },
    answer: "B",
    explanation: "Limited-risk systems carry transparency obligations (Article 50).",
  },

  // ---------------- ML FUNDAMENTALS ----------------
  {
    id: "ml-01",
    topic: "ml-fundamentals",
    stem: "A model performs excellently on training data but poorly on unseen test data. This is:",
    choices: {
      A: "Underfitting",
      B: "Overfitting",
      C: "Regularisation",
      D: "Normalisation",
    },
    answer: "B",
    explanation: "Overfitting — the model memorised the training set and fails to generalise.",
  },
  {
    id: "ml-02",
    topic: "ml-fundamentals",
    stem: "Which technique is MOST directly used to reduce overfitting?",
    choices: {
      A: "Increasing model complexity",
      B: "Removing the validation set",
      C: "Regularisation (e.g. L1/L2, dropout)",
      D: "Training for more epochs on the same data",
    },
    answer: "C",
    explanation: "Regularisation penalises complexity to improve generalisation.",
  },
  {
    id: "ml-03",
    topic: "ml-fundamentals",
    stem: "In supervised learning, the training data is characterised by:",
    choices: {
      A: "Having no labels",
      B: "Having input-output pairs (labelled data)",
      C: "Being generated by an agent's rewards",
      D: "Containing only images",
    },
    answer: "B",
    explanation: "Supervised learning uses labelled input-output pairs.",
  },

  // ---------------- GENAI / RAG ----------------
  {
    id: "genai-01",
    topic: "genai-rag",
    stem: "Retrieval-Augmented Generation (RAG) improves an LLM's output primarily by:",
    choices: {
      A: "Increasing the model's parameter count",
      B: "Retrieving relevant external documents and adding them to the context",
      C: "Removing the need for any training data",
      D: "Encrypting the model weights",
    },
    answer: "B",
    explanation:
      "RAG grounds responses in retrieved external knowledge, reducing hallucination.",
  },
  {
    id: "genai-02",
    topic: "genai-rag",
    stem: "In the context of LLMs, 'hallucination' refers to:",
    choices: {
      A: "The model crashing during inference",
      B: "The model generating plausible-sounding but factually incorrect content",
      C: "A hardware memory error",
      D: "An intentional adversarial attack",
    },
    answer: "B",
    explanation: "Confident but incorrect or fabricated output.",
  },
  {
    id: "genai-03",
    topic: "genai-rag",
    stem: "The transformer architecture, foundational to modern LLMs, is built around which core mechanism?",
    choices: {
      A: "Convolution",
      B: "Recurrence with LSTM cells",
      C: "Self-attention",
      D: "Decision trees",
    },
    answer: "C",
    explanation: "Self-attention ('Attention Is All You Need', 2017).",
  },
  {
    id: "genai-04",
    topic: "genai-rag",
    stem: "'Agentic AI' typically refers to systems that:",
    choices: {
      A: "Only classify static images",
      B: "Autonomously plan and execute multi-step tasks, often calling external tools",
      C: "Are prohibited under the AI Act by default",
      D: "Cannot use any external data",
    },
    answer: "B",
    explanation: "Agents plan, act, and use tools toward a goal.",
  },

  // ---------------- MLOPS ----------------
  {
    id: "mlops-01",
    topic: "mlops",
    stem: "'Model drift' in a production ML system refers to:",
    choices: {
      A: "The model file moving to another server",
      B: "Degradation of model performance as real-world data diverges from training data",
      C: "A version-control merge conflict",
      D: "GPU memory fragmentation",
    },
    answer: "B",
    explanation: "Data/concept drift degrades accuracy over time.",
  },
  {
    id: "mlops-02",
    topic: "mlops",
    stem: "Which MLOps practice MOST directly addresses model drift?",
    choices: {
      A: "One-time deployment with no further checks",
      B: "Continuous monitoring with automated retraining triggers",
      C: "Deleting the validation set after launch",
      D: "Hard-coding predictions",
    },
    answer: "B",
    explanation: "Monitoring plus retraining is the standard mitigation for drift.",
  },
  {
    id: "mlops-03",
    topic: "mlops",
    stem: "A model registry in an MLOps pipeline is primarily used to:",
    choices: {
      A: "Store user passwords",
      B: "Version, track, and manage trained model artefacts and their metadata",
      C: "Replace the need for testing",
      D: "Serve the web front-end",
    },
    answer: "B",
    explanation: "A central versioned store for models and their lineage.",
  },

  // ---------------- TRUSTWORTHY AI ----------------
  {
    id: "trust-01",
    topic: "trustworthy-ai",
    stem: "'Explainability' (XAI) in an AI system refers to the ability to:",
    choices: {
      A: "Make the model run faster",
      B: "Provide human-understandable reasons for the model's outputs",
      C: "Encrypt the training data",
      D: "Reduce the model size",
    },
    answer: "B",
    explanation: "Interpretable, human-understandable justifications for decisions.",
  },
  {
    id: "trust-02",
    topic: "trustworthy-ai",
    stem: "Under GDPR Article 22, individuals have the right:",
    choices: {
      A: "To never be shown any advertising",
      B: "Not to be subject to a decision based solely on automated processing that significantly affects them (with safeguards)",
      C: "To free access to any AI model",
      D: "To delete any public dataset",
    },
    answer: "B",
    explanation:
      "A right regarding solely-automated decisions with legal or similarly significant effect.",
  },
  {
    id: "trust-03",
    topic: "trustworthy-ai",
    stem: "Which is a pillar of the EU's 'Trustworthy AI' guidelines?",
    choices: {
      A: "Maximising profit above all",
      B: "Human agency and oversight",
      C: "Avoiding all documentation",
      D: "Removing accountability",
    },
    answer: "B",
    explanation: "Human agency and oversight is a core requirement of Trustworthy AI.",
  },

  // ---------------- POLICY ----------------
  {
    id: "policy-01",
    topic: "policy",
    stem: "The body established under the AI Act to help ensure consistent application across the EU and oversee GPAI models is the:",
    choices: {
      A: "European Central Bank",
      B: "European AI Office",
      C: "European Court of Auditors",
      D: "European Data Protection Board (sole authority)",
    },
    answer: "B",
    explanation:
      "The AI Office, within the Commission, oversees GPAI and coordinates application.",
  },
  {
    id: "policy-02",
    topic: "policy",
    stem: "A key EU policy rationale for regulating AI via a single Regulation (rather than per Member State) is to:",
    choices: {
      A: "Increase divergence between national rules",
      B: "Ensure a harmonised single market with consistent rules across the EU",
      C: "Ban all AI research",
      D: "Exempt EU institutions from any oversight",
    },
    answer: "B",
    explanation: "Harmonisation of the internal market is the stated legal basis.",
  },

  // ---------------- VERBAL (seed) ----------------
  {
    id: "verbal-01",
    topic: "verbal",
    stem: "Passage: 'Moldavia is a region in north-eastern Romania. A former independent state until its union with Wallachia in 1859, Moldavia now forms much of the modern state of Romania.'\n\nStatement: Moldavia was an independent state before 1859.",
    choices: {
      A: "True",
      B: "False",
      C: "Cannot say",
      D: "-",
    },
    answer: "A",
    explanation:
      "The passage states it was a 'former independent state until its union ... in 1859'. Answer only from the passage.",
  },

  // ---------------- NUMERICAL (seed — demonstrates workedSolution guardrail) ----------------
  {
    id: "numerical-01",
    topic: "numerical",
    stem: "Solar output rose from 138 to 149 GWh; population rose 1.1% over the same period. Approx. change in per-capita solar output?",
    choices: {
      A: "5.9%",
      B: "6.8%",
      C: "7.9%",
      D: "9.1%",
    },
    answer: "B",
    explanation: "Per-capita change ≈ output growth minus population growth.",
    workedSolution:
      "Output growth = 149/138 − 1 ≈ 0.0797 = 7.97%. Per-capita ≈ 7.97% − 1.1% ≈ 6.87% ≈ 6.8% → B.",
  },
];
