import type { Question } from "@/lib/types";

// Seed bank. Self-authored, EPSO-style single-best-answer MCQs.
// NOT official EPSO material. The "generate more" feature appends to this at runtime.
export const SEED_QUESTIONS: Question[] = [
  // ---------------- EU AI ACT ----------------
  {
    id: "aiact-01",
    topic: "ai-act",
    stem: "Under the EU AI Act (Reg. 2024/1689), which risk category do AI systems used for social scoring by public authorities fall into?",
    choices: {
      A: "High-risk, permitted with conformity assessment",
      B: "Limited-risk, transparency obligations only",
      C: "Prohibited (unacceptable risk)",
      D: "Minimal-risk, no obligations",
    },
    answer: "C",
    explanation:
      "Social scoring by public authorities is a prohibited practice under Article 5 (unacceptable risk).",
  },
  {
    id: "aiact-02",
    topic: "ai-act",
    stem: "The EU AI Act classifies AI systems primarily according to:",
    choices: {
      A: "The programming language used",
      B: "The level of risk they pose",
      C: "The size of the provider organisation",
      D: "The country of deployment",
    },
    answer: "B",
    explanation:
      "It is a risk-based framework: unacceptable / high / limited / minimal risk.",
  },
  {
    id: "aiact-03",
    topic: "ai-act",
    stem: "Which of the following is a 'high-risk' AI system under the AI Act?",
    choices: {
      A: "A spam filter",
      B: "An AI system used to evaluate candidates in recruitment",
      C: "A video-game NPC behaviour engine",
      D: "A product-recommendation widget",
    },
    answer: "B",
    explanation:
      "AI used in employment/recruitment is listed as high-risk in Annex III.",
  },
  {
    id: "aiact-04",
    topic: "ai-act",
    stem: "General-Purpose AI (GPAI) models with 'systemic risk' are presumed when training compute exceeds a threshold measured in:",
    choices: {
      A: "Number of parameters only",
      B: "Floating-point operations (FLOPs) used in training",
      C: "Gigabytes of training data",
      D: "Number of end users",
    },
    answer: "B",
    explanation:
      "The Act uses a cumulative training-compute (FLOPs) threshold to presume systemic risk.",
  },
  {
    id: "aiact-05",
    topic: "ai-act",
    stem: "Which obligation applies to a limited-risk system such as a chatbot interacting with humans?",
    choices: {
      A: "Full conformity assessment before market placement",
      B: "Transparency: users must be informed they are interacting with an AI",
      C: "Prohibition",
      D: "No obligation whatsoever",
    },
    answer: "B",
    explanation: "Limited-risk systems carry transparency obligations (Article 50).",
  },

  // ---------------- ML FUNDAMENTALS ----------------
  {
    id: "ml-01",
    topic: "ml-fundamentals",
    stem: "A model performs excellently on training data but poorly on unseen test data. This is:",
    choices: {
      A: "Underfitting",
      B: "Overfitting",
      C: "Regularisation",
      D: "Normalisation",
    },
    answer: "B",
    explanation: "Overfitting — the model memorised the training set and fails to generalise.",
  },
  {
    id: "ml-02",
    topic: "ml-fundamentals",
    stem: "Which technique is MOST directly used to reduce overfitting?",
    choices: {
      A: "Increasing model complexity",
      B: "Removing the validation set",
      C: "Regularisation (e.g. L1/L2, dropout)",
      D: "Training for more epochs on the same data",
    },
    answer: "C",
    explanation: "Regularisation penalises complexity to improve generalisation.",
  },
  {
    id: "ml-03",
    topic: "ml-fundamentals",
    stem: "In supervised learning, the training data is characterised by:",
    choices: {
      A: "Having no labels",
      B: "Having input-output pairs (labelled data)",
      C: "Being generated by an agent's rewards",
      D: "Containing only images",
    },
    answer: "B",
    explanation: "Supervised learning uses labelled input-output pairs.",
  },

  // ---------------- GENAI / RAG ----------------
  {
    id: "genai-01",
    topic: "genai-rag",
    stem: "Retrieval-Augmented Generation (RAG) improves an LLM's output primarily by:",
    choices: {
      A: "Increasing the model's parameter count",
      B: "Retrieving relevant external documents and adding them to the context",
      C: "Removing the need for any training data",
      D: "Encrypting the model weights",
    },
    answer: "B",
    explanation:
      "RAG grounds responses in retrieved external knowledge, reducing hallucination.",
  },
  {
    id: "genai-02",
    topic: "genai-rag",
    stem: "In the context of LLMs, 'hallucination' refers to:",
    choices: {
      A: "The model crashing during inference",
      B: "The model generating plausible-sounding but factually incorrect content",
      C: "A hardware memory error",
      D: "An intentional adversarial attack",
    },
    answer: "B",
    explanation: "Confident but incorrect or fabricated output.",
  },
  {
    id: "genai-03",
    topic: "genai-rag",
    stem: "The transformer architecture, foundational to modern LLMs, is built around which core mechanism?",
    choices: {
      A: "Convolution",
      B: "Recurrence with LSTM cells",
      C: "Self-attention",
      D: "Decision trees",
    },
    answer: "C",
    explanation: "Self-attention ('Attention Is All You Need', 2017).",
  },
  {
    id: "genai-04",
    topic: "genai-rag",
    stem: "'Agentic AI' typically refers to systems that:",
    choices: {
      A: "Only classify static images",
      B: "Autonomously plan and execute multi-step tasks, often calling external tools",
      C: "Are prohibited under the AI Act by default",
      D: "Cannot use any external data",
    },
    answer: "B",
    explanation: "Agents plan, act, and use tools toward a goal.",
  },

  // ---------------- MLOPS ----------------
  {
    id: "mlops-01",
    topic: "mlops",
    stem: "'Model drift' in a production ML system refers to:",
    choices: {
      A: "The model file moving to another server",
      B: "Degradation of model performance as real-world data diverges from training data",
      C: "A version-control merge conflict",
      D: "GPU memory fragmentation",
    },
    answer: "B",
    explanation: "Data/concept drift degrades accuracy over time.",
  },
  {
    id: "mlops-02",
    topic: "mlops",
    stem: "Which MLOps practice MOST directly addresses model drift?",
    choices: {
      A: "One-time deployment with no further checks",
      B: "Continuous monitoring with automated retraining triggers",
      C: "Deleting the validation set after launch",
      D: "Hard-coding predictions",
    },
    answer: "B",
    explanation: "Monitoring plus retraining is the standard mitigation for drift.",
  },
  {
    id: "mlops-03",
    topic: "mlops",
    stem: "A model registry in an MLOps pipeline is primarily used to:",
    choices: {
      A: "Store user passwords",
      B: "Version, track, and manage trained model artefacts and their metadata",
      C: "Replace the need for testing",
      D: "Serve the web front-end",
    },
    answer: "B",
    explanation: "A central versioned store for models and their lineage.",
  },

  // ---------------- TRUSTWORTHY AI ----------------
  {
    id: "trust-01",
    topic: "trustworthy-ai",
    stem: "'Explainability' (XAI) in an AI system refers to the ability to:",
    choices: {
      A: "Make the model run faster",
      B: "Provide human-understandable reasons for the model's outputs",
      C: "Encrypt the training data",
      D: "Reduce the model size",
    },
    answer: "B",
    explanation: "Interpretable, human-understandable justifications for decisions.",
  },
  {
    id: "trust-02",
    topic: "trustworthy-ai",
    stem: "Under GDPR Article 22, individuals have the right:",
    choices: {
      A: "To never be shown any advertising",
      B: "Not to be subject to a decision based solely on automated processing that significantly affects them (with safeguards)",
      C: "To free access to any AI model",
      D: "To delete any public dataset",
    },
    answer: "B",
    explanation:
      "A right regarding solely-automated decisions with legal or similarly significant effect.",
  },
  {
    id: "trust-03",
    topic: "trustworthy-ai",
    stem: "Which is a pillar of the EU's 'Trustworthy AI' guidelines?",
    choices: {
      A: "Maximising profit above all",
      B: "Human agency and oversight",
      C: "Avoiding all documentation",
      D: "Removing accountability",
    },
    answer: "B",
    explanation: "Human agency and oversight is a core requirement of Trustworthy AI.",
  },

  // ---------------- POLICY ----------------
  {
    id: "policy-01",
    topic: "policy",
    stem: "The body established under the AI Act to help ensure consistent application across the EU and oversee GPAI models is the:",
    choices: {
      A: "European Central Bank",
      B: "European AI Office",
      C: "European Court of Auditors",
      D: "European Data Protection Board (sole authority)",
    },
    answer: "B",
    explanation:
      "The AI Office, within the Commission, oversees GPAI and coordinates application.",
  },
  {
    id: "policy-02",
    topic: "policy",
    stem: "A key EU policy rationale for regulating AI via a single Regulation (rather than per Member State) is to:",
    choices: {
      A: "Increase divergence between national rules",
      B: "Ensure a harmonised single market with consistent rules across the EU",
      C: "Ban all AI research",
      D: "Exempt EU institutions from any oversight",
    },
    answer: "B",
    explanation: "Harmonisation of the internal market is the stated legal basis.",
  },

  // ---------------- VERBAL (seed) ----------------
  {
    id: "verbal-01",
    topic: "verbal",
    stem: "Passage: 'Moldavia is a region in north-eastern Romania. A former independent state until its union with Wallachia in 1859, Moldavia now forms much of the modern state of Romania.'\n\nStatement: Moldavia was an independent state before 1859.",
    choices: {
      A: "True",
      B: "False",
      C: "Cannot say",
      D: "-",
    },
    answer: "A",
    explanation:
      "The passage states it was a 'former independent state until its union ... in 1859'. Answer only from the passage.",
  },

  // ---------------- VERBAL — READING COMPREHENSION (seed) ----------------
  // Real EPSO-format reference items (passage + "Which statement is correct?" +
  // 4 full-sentence options). Explanations name each distractor's trap type —
  // that naming IS the training signal for spotting them under time pressure.
  {
    id: "verbalrc-01",
    topic: "verbal-rc",
    stem:
      "Genetic testing is a medical procedure that identifies changes or specific problems in genes and chromosomes. Most of the time, genetic testing is used to identify inherited illnesses such as haemophilia. The results of a genetic test can confirm or rule out a suspected condition or help determine a person's chance of developing or passing on a genetic illness. Several hundred genetic tests are currently in use and more are being developed. Because testing has both benefits and limitations, the decision about whether to be tested is voluntary. A counsellor can give advice and information about the testing, but many people still doubt its usefulness. They believe that genetic testing is associated only with the heredity of fatal conditions and, on that basis, do not want to know.\n\nWhich of the following statements is correct?",
    choices: {
      A: "Genetic testing is generally used on healthy people",
      B: "Genetic testing can be used to establish the likelihood of someone developing certain illnesses in the future",
      C: "Genetic testing is not very useful because it is voluntary",
      D: "Several hundred genetic tests are carried out each year",
    },
    answer: "B",
    explanation:
      "B is the faithful paraphrase: the passage says testing can 'help determine a person's chance of developing or passing on a genetic illness'. A is OVERREACH — the passage says testing identifies inherited illnesses, not that it is used on healthy people. C is BELIEF-AS-FACT plus an UNSTATED CAUSAL LINK — 'many people still doubt' is a reported opinion, and the passage never links usefulness to being voluntary. D is a QUANTITY/FREQUENCY SWAP — the text says several hundred tests are 'currently in use', not 'carried out each year'.",
  },
  {
    id: "verbalrc-02",
    topic: "verbal-rc",
    stem:
      "The gambel oak is a small deciduous tree which typically grows at altitudes of 1 700 to 2 400 metres above sea level. Widespread in the foothills of the central south-western United States, it tends to grow where rainfall averages between 30 and 60 centimetres per year. Gambel oaks flourish on hillsides with thin, rocky, alkaline soil where other plant species are limited. They can survive in richer soils, but they face more competition for resources from other plants. Gambel oaks have adapted to wet springs and hot, dry summers - conditions which are also favourable to fires. However, even if badly burned, it can re-establish itself quickly from its roots below ground and handles drought conditions well.\n\nWhich of the following statements is correct?",
    choices: {
      A: "Gambel oaks flourish on hillsides where no other plants survive",
      B: "Gambel oaks are common across the USA",
      C: "Gambel oaks do better in environments where there is less competition from other plants",
      D: "The gambel oak cannot be killed by either brush fire or drought",
    },
    answer: "C",
    explanation:
      "C is the faithful paraphrase: the passage says they flourish where 'other plant species are limited' and in richer soils 'face more competition' - so less competition suits them. A is OVERREACH — 'limited' other species is not 'no other plants survive'. B is a SCOPE SWAP — the passage says 'the central south-western United States', a specific region, not 'across the USA'. D is OVERREACH TO AN ABSOLUTE — the text says it 're-establishes itself quickly' after burning and 'handles drought well', which is resilience, not being impossible to kill.",
  },

  // ---------------- NUMERICAL (seed — real EPSO format: table + A-E) ----------------
  // Data-table + calculation + 5 options (E = "None of the above"). A calculator
  // is provided in the real test, so figures can be non-trivial. Each carries a
  // worked solution and an ordered step breakdown for the untimed learn-mode.
  {
    id: "numerical-01",
    topic: "numerical",
    table: {
      caption: "National solar generation",
      headers: ["Year", "Output (GWh)", "Population (m)"],
      rows: [
        ["2000", "138", "10.0"],
        ["2003", "149", "10.11"],
      ],
    },
    stem:
      "Solar output rose from 138 to 149 GWh while the population grew by 1.1% over the same period. Approximately what was the change in per-capita solar output?",
    choices: {
      A: "5.9%",
      B: "6.8%",
      C: "7.9%",
      D: "9.1%",
      E: "None of the above",
    },
    answer: "B",
    explanation:
      "Per-capita change ≈ output growth minus population growth. Output grew ~7.97%, population 1.1%, so per-capita ≈ 6.8% (B). C (7.9%) is the trap of forgetting the population adjustment.",
    workedSolution:
      "Output growth = 149/138 − 1 ≈ 0.0797 = 7.97%. Per-capita ≈ 7.97% − 1.1% ≈ 6.87% ≈ 6.8% → B.",
    steps: [
      "Find the solar output growth: 149 / 138 = 1.0797.",
      "Convert to a percentage change: 1.0797 − 1 = 0.0797 ≈ 7.97%.",
      "Per-capita change ≈ output growth − population growth = 7.97% − 1.1%.",
      "7.97% − 1.1% ≈ 6.87%, which rounds to 6.8% → answer B.",
    ],
  },
  {
    id: "numerical-02",
    topic: "numerical",
    table: {
      caption: "R & D expenditure by country",
      headers: ["Country", "GDP per head 2000 (€)", "R&D (% of GDP) 2000", "R&D (% of GDP) 2003"],
      rows: [
        ["Belgium", "19 330", "1.97", "1.89"],
        ["Finland", "21 582", "3.34", "3.43"],
        ["France", "18 874", "2.15", "2.17"],
      ],
    },
    stem:
      "If Belgium's GDP per head increased by 3% between 2000 and 2003, and R&D spending is the stated percentage of GDP, by approximately how much did Belgium's per-head R&D spend change over the period?",
    choices: {
      A: "It fell by about 1.2%",
      B: "It rose by about 1.2%",
      C: "It rose by about 3.0%",
      D: "It fell by about 4.1%",
      E: "None of the above",
    },
    answer: "A",
    explanation:
      "Per-head R&D = GDP per head × R&D%. 2000: 19330 × 1.97% = 380.8. 2003: (19330 × 1.03) × 1.89% = 19910 × 1.89% = 376.3. Change = 376.3/380.8 − 1 ≈ −1.2%, a small fall (A). The R&D-share drop (1.97→1.89) outweighs the 3% GDP rise.",
    workedSolution:
      "2000 per-head R&D = 19330 × 0.0197 = 380.8. 2003 GDP/head = 19330 × 1.03 = 19910. 2003 per-head R&D = 19910 × 0.0189 = 376.3. Change = 376.3/380.8 − 1 ≈ −0.0118 ≈ −1.2% → A.",
    steps: [
      "2000 per-head R&D = 19330 × 1.97% = 19330 × 0.0197 = 380.8 €.",
      "2003 GDP per head = 19330 × 1.03 = 19910 €.",
      "2003 per-head R&D = 19910 × 1.89% = 19910 × 0.0189 = 376.3 €.",
      "Change = 376.3 / 380.8 − 1 ≈ −0.0118 = −1.2% → a fall of about 1.2%, answer A.",
    ],
  },
];
